apiVersion: v1
kind: Service
metadata:
  name: node-jenkins-demo-service
spec:
  type: NodePort
  selector:
    app: node-jenkins-demo
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080 